### ISSUE TITLE
Issues found in  "Informatics Metric i2b2-ACT MSSQL.sql"

### ISSUE THREAD

**Issue by edneu** [ncats/CTSA-Metrics#11]
There are   two issues with the script that I had to modify in order to make it run:
--
*Line 127 - incorrect syntax for   commenting (i.e., should replace '//' with '--')
*Line 144 - incorrect table name (i.e.,   it should be NCATS_DEMOGRAPHICS from the metadata table rather than   PCORNET_DEMO. The PCORNET_DEMO would be a correct table name for PCORNET   script, but not for i2b2-ACT script.)
 
There is one more issue, which didn't   stop me from executing the script, but it doesn't do anything useful:
*Line 88 - the sql command   requres 'lower(c_operator) in (''in'', ''='')'

**Comment by KenGersing** [comment]
Thank you for your help I changed both line 127 and 144.  I left 88 as is
