### ISSUE TITLE
i2b2-ACT MSSQL error

### ISSUE THREAD

**Issue by wendyz99** [ncats/CTSA-Metrics#12]
Hello. I ran "Informatics Metric i2b2-ACT MSSQL.sql" and got the following results:

(9 row(s) affected)
2722917

(1 row(s) affected)

(3 row(s) affected)
Msg 208, Level 16, State 1, Line 128
Invalid object name 'NCATS_DEMOGRAPHICS'.
Msg 4902, Level 16, State 1, Procedure CTSA_QIMCOUNT, Line 160
Cannot find the object "ontInOperator" because it does not exist or you do not have permissions.

(9 row(s) affected)

**Comment by wendyz99** [comment]
Issue solved.

**Comment by aaraya1516** [comment]
How was this issue resolved? I'm currently having this problem.
