### ISSUE TITLE
ACT/i2b2 scripts are missing ACT in their name

### ISSUE THREAD

**Issue by mim18** [ncats/CTSA-Metrics#19]
Many apologies Reid.
Would you mind renaming the i2b2/ACT scripts?
CLICMetric2019Oracle.sql -> CLICMetric2019ACTi2b2Oracle.sql
CLICMetric2019MSSql.sql -> CLICMetric2019ACTi2b2MSSql.sql

**Comment by reidsimon** [comment]
Please submit a PR and I will merge.
