### ISSUE TITLE
C1: Time constraints

### ISSUE THREAD

**Issue by mgkahn** [ncats/CTSA-Metrics#24]
C1: Document header says "at any time" but spreadsheet says "in time frame". Should the search for a lab test be limited to those tests done within one-year/five-year windows or not? 

Currently I am only limiting the cohort of patients or encounters by the one-year/five-year windows but I am NOT limiting the search for labs by the same time windows. Should I?

This would change the meaning of C1 to be: **Patients seen in one year** who have at least one lab test (from any coding system) **that occurred in one year.**  My current logic is patients seen in one year who have at least one lab test (from any coding system) **that occurred at any time.** (limiting the "one-year" only to the patient cohort, not the lab test).

**Comment by ams219** [comment]
Q1: It should be in the "time frame" one-year and five-year.

Q2: I'm guessing that we should be limiting the search by the same time windows. I'm not the final word.

**Comment by mgkahn** [comment]
The question is what is "it" in your answer: the patients/encounters in the time frame? The lab test in the time frame? Both?

Thinking as an investigator: I agree with you that the most useful answer is both -- for a study using patients seen in 2020 (cohort time restriction), how much 2020 lab data can I get from the database (lab domain time restriction).

**Comment by ams219** [comment]
Whenever possible, time frames should be both one-year and five-years for the measures.

**Comment by mim18** [comment]
Use the time frames to constrain both your numerator and denominator.
