### ISSUE TITLE
Error when running script line 379

### ISSUE THREAD

**Issue by mwennberg** [ncats/CTSA-Metrics#30]
I receive an error on this line when running the script. Should enc1y.ADMIT_DATE be changed to enc5y.ADMIT_DATE based on the table alias referenced in the select statement? 

https://github.com/ncats/CTSA-Metrics/blob/6d8612b256c44e742c6fde8005280cf8aa660067/Informatics%20Metric%20PCORnet%20Oracle.sql#L379

**Comment by empfff** [comment]
Good catch, just fixed this, thanks!
