### ISSUE TITLE
Hard-coded 'UNIQUE_TOTAL_PATIENTS' value in Informatics Metric PCORnet MSSQL

### ISSUE THREAD

**Issue by bfurner** [ncats/CTSA-Metrics#5]
Line 45 of the following file contains two hard-coded values for UNIQUE_TOTAL_PATIENTS (10):

https://github.com/ncats/CTSA-Metrics/blob/master/Informatics%20Metric%20PCORnet%20MSSQL

Select 'Diagnosis as ICD/SNOMED' as domain, num.cnt as Patients_with_Standards, 10 as UNIQUE_TOTAL_PATIENTS, 100.0 * num.cnt/10 as Percent_Standards, 'Not Applicable' as Values_Present

should be changed to

Select 'Diagnosis as ICD/SNOMED' as domain, num.cnt as Patients_with_Standards, den.cnt as UNIQUE_TOTAL_PATIENTS, 100.0 * num.cnt/den.cnt as Percent_Standards, 'Not Applicable' as Values_Present

**Comment by KenGersing** [comment]
Script was updated thank you for the test and the clear directions on the error
