### ISSUE TITLE
Datetime Issue in Query for Demo Age/DOB Measure

### ISSUE THREAD

**Issue by cukarthik** [ncats/CTSA-Metrics#6]
Since birth_datetime is an optional field in the current OMOP version, I would suggest modifying the this [line](https://github.com/ncats/CTSA-Metrics/blob/4131059768fd3ce0d0801fef7d453d6160dd5154/Informatics%20Metric%20OMOP%20MSSQL.sql#L39) to have an 'OR' statement that includes the commented lines of code. 

So the query would look like this:

```
		SELECT 'Demo Age/DOB' AS Domain,
		CAST(COUNT(DISTINCT D.person_id) as Float) AS 'Patients with Standards'
		FROM Person D
		-- We may want to alter this to be only Year of birth present at this time Year, Month and Day are required in order to count
		Where D.birth_datetime  is NOT NULL OR (D.Year_of_Birth  is NOT NULL
			and  D.month_of_Birth is NOT NULL
			and  D.Day_of_Birth  is NOT NULL)
```

**Comment by KenGersing** [comment]
The script was modified to only check for the year of birth.
