### ISSUE TITLE
Issue with Column Names for Observations Present - PCORnet Oracle Code

### ISSUE THREAD

**Issue by mwennberg** [ncats/CTSA-Metrics#7]
Running the latest PCORnet Oracle code, [44b05d4](https://github.com/ncats/CTSA-Metrics/commit/44b05d424570c8e33d8a1878b9b82ae27ba638a5),  provided me with errors. I updated the column names as follows and then it ran successfully: 
` select 'Observations Present' AS domain, null as Patients_with_Standards, null as UNIQUE_TOTAL_PATIENTS, null as Percent_Standards
    , Case  When Count(*) = 0 then 'No Observation' 
    else 'Observations Present' 
    end as values_present	
From Vital`

**Comment by KenGersing** [comment]
Merged code closing issues
